apiVersion: apps/v1beta2
kind: Deployment
metadata:
    name: mongo-krapp-deployment
spec:
  replicas: 2
  selector:
      matchLabels:
          app: node-express-mongo
  template:
    metadata:
      labels: 
        app: node-express-mongo
    spec:
      containers:
        - name: mongo-krapp
          image: mongo:latest
          ports:
            - containerPort: 27017
              hostPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          gcePersistentDisk: 
            pdName: mongo-disk
            