apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
    name: krapp-replicaset
spec:
  replicas: 2
  selector:
      matchLabels:
          app: node-express-krapp
  template:
    metadata:
      labels: 
        app: node-express-krapp
    spec:
      containers:
        - name: krapp
          image: aravi123/krappnode:latest
          ports:
            - containerPort: 3000